[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform[viz]~=0.15.0",
    "ipympl",
    "ipywidgets",
    "mpl-interactions",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "missing-return-type-private-function",
    "unused-function-argument",
    "complex-structure",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "late-future-import",
    "undefined-name",
    "single-line-implicit-string-concatenation",
    "N80",
    "mixed-case-variable-in-global-scope",
    "PLR091",
    "magic-value-comparison",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
    "private-member-access",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.uv.workspace]
