[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform",
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "tensorwaves",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "ANN20",
    "unused-method-argument",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "late-future-import",
    "FBT00",
    "single-line-implicit-string-concatenation",
    "non-lowercase-variable-in-function",
    "non-ascii-name",
    "too-many-arguments",
    "too-many-positional-arguments",
    "global-statement",
    "non-self-return-type",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
]
select = ["ALL"]

[tool.ruff.lint.flake8-self]
ignore-names = ["_print"]

[tool.uv.workspace]
