[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform[viz] @ git+https://github.com/ComPWA/ampform@3ed3ed5",
    "ipywidgets",
    "sympy~=1.9.0",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "missing-return-type-undocumented-public-function",
    "unused-method-argument",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "ambiguous-variable-name",
    "late-future-import",
    "single-line-implicit-string-concatenation",
    "import-outside-top-level",
    "import-private-name",
    "too-many-locals",
    "magic-value-comparison",
    "non-self-return-type",
    "float-equality-comparison",
    "assert",
    "if-else-block-instead-of-if-exp",
    "typing-only-standard-library-import",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.ruff.lint.flake8-self]
ignore-names = ["_print"]

[tool.uv.workspace]
