[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN001",
    "ANN201",
    "COM812",
    "CPY001",
    "D",
    "F404",
    "F821",
    "ISC001",
    "PLC2401",
    "PLC2701",
    "PLR0913",
    "PLR0917",
    "PLR2004",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["display"]
