[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "jax",
    "matplotlib",
    "polarimetry-lc2pkpi==0.0.11",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-type-function-argument",
    "missing-return-type-undocumented-public-function",
    "unnecessary-collection-call",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "late-future-import",
    "undefined-name",
    "single-line-implicit-string-concatenation",
    "non-ascii-name",
    "import-private-name",
    "too-many-arguments",
    "too-many-positional-arguments",
    "magic-value-comparison",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.uv.workspace]
