[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "pdg",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "late-future-import",
    "single-line-implicit-string-concatenation",
    "try-except-in-loop",
    "magic-value-comparison",
    "redefined-loop-name",
    "print",
]
select = ["ALL"]

[tool.uv.workspace]
