[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "nbformat>=4.2.0",
    "plotly~=5.0",
    "sympy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-type-function-argument",
    "missing-return-type-undocumented-public-function",
    "unused-function-argument",
    "unnecessary-collection-call",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "single-line-implicit-string-concatenation",
    "non-lowercase-variable-in-function",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.uv.workspace]
