[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform[viz]~=0.15.0",
    "ipywidgets",
    "matplotlib",
    "tensorwaves[jax,pwa]",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "ANN20",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "line-too-long",
    "ambiguous-variable-name",
    "late-future-import",
    "FBT00",
    "single-line-implicit-string-concatenation",
    "non-lowercase-variable-in-function",
    "non-ascii-name",
    "too-many-arguments",
    "too-many-positional-arguments",
    "assert",
    "TC00",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.uv.workspace]
