[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform",
    "sympy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-copyright-notice",
    "undocumented-public-function",
    "incorrect-blank-line-before-class",
    "multi-line-summary-first-line",
]
select = ["ALL"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.uv.workspace]
