[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform",
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "nbformat",
    "plotly~=5.0",
    "sympy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-type-function-argument",
    "missing-return-type-undocumented-public-function",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "lambda-assignment",
    "boolean-positional-value-in-call",
    "single-line-implicit-string-concatenation",
    "non-lowercase-variable-in-function",
    "non-ascii-name",
    "global-statement",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.uv.workspace]
