[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform",
    "black",
    "matplotlib",
    "scipy",
    "sympy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "ANN20",
    "unused-method-argument",
    "unnecessary-collection-call",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "single-line-implicit-string-concatenation",
    "import-private-name",
]
select = ["ALL"]

[tool.ruff.lint.flake8-self]
ignore-names = ["_print"]

[tool.uv.workspace]
