[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "iminuit",
    "ipywidgets",
    "matplotlib",
    "pandas",
    "phasespace",
    "scipy~=1.15.0",
    "tqdm",
    "vector",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "missing-return-type-undocumented-public-function",
    "unused-function-argument",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "line-too-long",
    "late-future-import",
    "single-line-implicit-string-concatenation",
    "N80",
    "mixed-case-variable-in-global-scope",
    "too-many-arguments",
    "too-many-statements",
    "too-many-positional-arguments",
    "global-statement",
]
select = ["ALL"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.uv.workspace]
