[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.9.0"
dependencies = [
    "ampform~=0.10.5",
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "mpl-interactions",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "missing-return-type-private-function",
    "unused-method-argument",
    "complex-structure",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "late-future-import",
    "future-rewritable-type-annotation",
    "repeated-append",
    "single-line-implicit-string-concatenation",
    "N80",
    "PLR091",
    "non-self-return-type",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
    "private-member-access",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.uv.workspace]
