[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "COM812",
    "CPY001",
    "D",
    "E741",
    "F404",
    "FBT00",
    "ISC001",
    "N806",
    "N816",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["display"]
