[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform[viz]~=0.15.0",
    "matplotlib",
    "scipy",
    "tensorwaves[jax,pwa]",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-type-function-argument",
    "missing-return-type-undocumented-public-function",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "line-too-long",
    "late-future-import",
    "single-line-implicit-string-concatenation",
    "non-lowercase-variable-in-function",
    "too-many-locals",
]
select = ["ALL"]

[tool.uv.workspace]
