[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform~=0.15.0",
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "tensorwaves[jax]",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "ANN20",
    "ARG00",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "docstring-missing-returns",
    "line-too-long",
    "late-future-import",
    "boolean-type-hint-positional-argument",
    "boolean-default-value-positional-argument",
    "line-contains-hack",
    "single-line-implicit-string-concatenation",
    "N80",
    "N81",
    "non-ascii-name",
    "too-many-arguments",
    "too-many-positional-arguments",
    "magic-value-comparison",
    "global-statement",
    "redefined-loop-name",
    "assert",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.ruff.lint.flake8-self]
ignore-names = [
    "_latex",
    "_print",
]

[tool.uv.workspace]
