[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.11.0"
dependencies = [
    "black",
    "jax",
    "numpy~=1.23.0",
    "sympy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-type-function-argument",
    "missing-return-type-undocumented-public-function",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "single-line-implicit-string-concatenation",
    "print",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.uv.workspace]
