[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform[viz]~=0.13.3",
    "numpy~=1.0",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "missing-return-type-undocumented-public-function",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "boolean-type-hint-positional-argument",
    "single-line-implicit-string-concatenation",
]
select = ["ALL"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.uv.workspace]
