[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "black",
    "jax",
    "matplotlib",
    "sympy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "ANN20",
    "unused-method-argument",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "single-line-implicit-string-concatenation",
    "print",
]
select = ["ALL"]

[tool.ruff.lint.flake8-self]
ignore-names = ["_print"]

[tool.ruff.lint.pep8-naming]
ignore-names = ["_print_*"]

[tool.uv.workspace]
