[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "ANN20",
    "ARG002",
    "COM812",
    "CPY001",
    "D",
    "ISC001",
    "T201",
]
select = ["ALL"]

[tool.ruff.lint.flake8-self]
ignore-names = ["_print"]

[tool.ruff.lint.pep8-naming]
ignore-names = ["_print_*"]
