[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform",
    "black",
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "mpl-interactions",
    "qrules",
    "scipy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "ANN20",
    "ARG00",
    "function-call-in-default-argument",
    "function-uses-loop-variable",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "lambda-assignment",
    "undefined-name",
    "single-line-implicit-string-concatenation",
    "non-lowercase-variable-in-function",
    "mixed-case-variable-in-global-scope",
    "import-private-name",
    "too-many-arguments",
    "too-many-positional-arguments",
    "missing-f-string-syntax",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
]
select = ["ALL"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.flake8-self]
ignore-names = ["_print"]

[tool.uv.workspace]
