[project]
name = "technical-report"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "ampform",
    "ampform-dpd",
    "ipykernel",
    "matplotlib",
    "numpy",
    "qrules",
    "tensorwaves",
]

[tool.uv.workspace]

[tool.uv.sources]
ampform = { git = "https://github.com/ComPWA/ampform", rev = "4fe79a57503abd70a5ab04fdc02cdd0d66dc99f3" }
ampform-dpd = { git = "https://github.com/ComPWA/ampform-dpd", rev = "03ca1cd1f45da3a5c23fde98d4546f747b1b2b95" }
