name: Run all notebooks

on:
  workflow_dispatch:
    inputs:
      notebook-selector:
        description: Relative path to notebooks
        required: false
        type: string

jobs:
  pytest:
    name: Test all notebooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: |
            ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
          path: |
            .pytest_cache
            ~/.cache/pip/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get -y install graphviz
          pip install .[test]
      - run: |
          function run-nbmake() {
            set +e
            pytest ${{ github.event.inputs.notebook-selector }}
            error_code=$?
            set -e
            echo "Pytest returned error code $error_code"
            case $error_code in
              0|5) return 0;;
              *) return $error_code;;
            esac
          }
          run-nbmake
        # cspell:ignore esac
