name: Run all notebooks

on:
  workflow_dispatch:
    inputs:
      notebook-selector:
        description: Relative path to notebooks
        required: false
        type: string

jobs:
  pytest:
    name: Test all notebooks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v5
      - name: Install graphviz
        run: sudo apt-get -y install graphviz
      - name: Run all notebooks
        run: uv run --extra test pytest ${{ github.event.inputs.notebook-selector }}
