name: Run all notebooks

on:
  workflow_dispatch:
    inputs:
      notebook-selector:
        description: Relative path to notebooks
        required: false
        type: string

jobs:
  pytest:
    name: Test all notebooks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: prefix-dev/setup-pixi@v0.8.5
      - name: Install graphviz
        run: sudo apt-get -y install graphviz
      - name: Run all notebooks
        run: pixi run pytest ${{ github.event.inputs.notebook-selector }}
